version: "3.9"

services:
  mongo:
    image: mongo
    container_name: chatcord
    ports:
      - "27017:27017"
    networks:
      - backend

  redis:
    image: redislabs/redismod:latest
    container_name: redis-chatcord
    environment:
      - PY_MONGO_URL=${PY_MONGO_URL}
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
